# Admin App - admin.thesoaringeagles.ca
server {
    listen 80;
    server_name admin.thesoaringeagles.ca;
    return 302 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    ssl_certificate         /etc/ssl/thesoaringeagles.ca.pem;
    ssl_certificate_key     /etc/ssl/thesoaringeagles.ca.key.pem;

    server_name admin.thesoaringeagles.ca;

    location / {
        proxy_pass http://localhost:3003;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}

# Viewer App - viewer.thesoaringeagles.ca
server {
    listen 80;
    server_name viewer.thesoaringeagles.ca;
    return 302 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    ssl_certificate         /etc/ssl/thesoaringeagles.ca.pem;
    ssl_certificate_key     /etc/ssl/thesoaringeagles.ca.key.pem;

    server_name viewer.thesoaringeagles.ca;

    location / {
        proxy_pass http://localhost:3004;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
